export * from './auth.interface'
export * from './document.interface'
export * from './userData.interface'
export * from './register.interface'
export * from './news.interface'
export * from './faq.interface'